In [2]:
import pandas as pd

In [3]:
bloodReport = pd.read_csv(r"C:\Users\direk\OneDrive\Desktop\data_diseasePredictor\blood_report.csv")
bloodReport = bloodReport.drop("risk_label", axis=1)
bloodReport.head()

     wbc   rbc  hemoglobin  hematocrit  platelets  glucose  creatinine    bun
0   8.25  5.17       16.60       50.58     241.24    90.71        0.52   8.73
1  12.31  5.56       15.89       47.11     267.77    94.68        0.73   5.40
2  14.05  4.24       14.59       42.95     235.38    81.69        0.82   8.31
3   9.78  5.03       13.53       40.59     259.60    78.88        1.28  12.93
4   7.15  4.54       15.55       46.47     180.32    74.15        1.01   8.61

In [4]:
def diabetes_risk(glucose):
    if glucose >= 200:
        return "Critical"
    elif glucose >= 126:
        return "High"
    elif glucose >= 100:
        return "Medium"
    else:
        return "Low"


def anemia_risk(hb):
    if hb < 7:
        return "Critical"
    elif hb < 11:
        return "High"
    elif hb < 13:
        return "Medium"
    else:
        return "Low"


def infection_risk(wbc):
    if wbc > 20:
        return "Critical"
    elif wbc > 11:
        return "High"
    elif wbc < 4:
        return "Low"
    else:
        return "Normal"

In [8]:
bloodReport["diabetes_risk"] = bloodReport["glucose"].apply(diabetes_risk)
bloodReport["anemia_risk"] = bloodReport["hemoglobin"].apply(anemia_risk)
bloodReport["infection_risk"] = bloodReport["wbc"].apply(infection_risk)

bloodReport.head()

,wbc,rbc,hemoglobin,hematocrit,platelets,glucose,creatinine,bun,diabetes_risk,anemia_risk,infection_risk,diabetes_risk_num,anemia_risk_num,infection_risk_num
0,8.25,5.17,16.60,50.58,241.24,90.71,0.52,8.73,Low,Low,Normal,0,0,1
1,12.31,5.56,15.89,47.11,267.77,94.68,0.73,5.40,Low,Low,High,0,0,2
2,14.05,4.24,14.59,42.95,235.38,81.69,0.82,8.31,Low,Low,High,0,0,2
3,9.78,5.03,13.53,40.59,259.60,78.88,1.28,12.93,Low,Low,Normal,0,0,1
4,7.15,4.54,15.55,46.47,180.32,74.15,1.01,8.61,Low,Low,Normal,0,0,1

In [6]:
LABEL_MAPPING = {
    "Low": "low",
    "Normal": "moderate",
    "Medium": "moderate",
    "High": "high",
    "Critical": "critical"
}

NUM_MAPPING = {
    "low": 0,
    "moderate": 1,
    "high": 2,
    "critical": 3
}

In [7]:
bloodReport["diabetes_risk"] = bloodReport["diabetes_risk"].map(LABEL_MAPPING)
bloodReport["anemia_risk"] = bloodReport["anemia_risk"].map(LABEL_MAPPING)
bloodReport["infection_risk"] = bloodReport["infection_risk"].map(LABEL_MAPPING)
bloodReport["diabetes_risk_num"] = bloodReport["diabetes_risk"].map(NUM_MAPPING)
bloodReport["anemia_risk_num"] = bloodReport["anemia_risk"].map(NUM_MAPPING)
bloodReport["infection_risk_num"] = bloodReport["infection_risk"].map(NUM_MAPPING)
bloodReport.head()

,wbc,rbc,hemoglobin,hematocrit,platelets,glucose,creatinine,bun,diabetes_risk,anemia_risk,infection_risk,diabetes_risk_num,anemia_risk_num,infection_risk_num
0,8.25,5.17,16.60,50.58,241.24,90.71,0.52,8.73,low,low,moderate,0,0,1
1,12.31,5.56,15.89,47.11,267.77,94.68,0.73,5.40,low,low,high,0,0,2
2,14.05,4.24,14.59,42.95,235.38,81.69,0.82,8.31,low,low,high,0,0,2
3,9.78,5.03,13.53,40.59,259.60,78.88,1.28,12.93,low,low,moderate,0,0,1
4,7.15,4.54,15.55,46.47,180.32,74.15,1.01,8.61,low,low,moderate,0,0,1