In [7]:
import pandas as pd
lipidProfile = pd.read_csv(r"C:\Users\direk\OneDrive\Desktop\data_diseasePredictor\lipid_profile.csv")
lipidProfile = lipidProfile.drop("risk_label", axis=1)
lipidProfile.head()

   total_cholesterol    hdl     ldl  triglycerides   vldl
0             213.34  44.15  146.48         100.16  20.53
1             175.65  62.89   91.62         103.54  21.51
2             268.11  55.96  179.58         160.14  37.01
3             231.00  74.90  140.59         105.42  20.53
4             255.20  64.16  166.93          95.75  18.51

In [8]:
def heart_risk(row):
    score = 0
    
    if row["total_cholesterol"] > 280:
        return "Critical"
    
    if row["total_cholesterol"] > 200:
        score += 1
    if row["ldl"] > 130:
        score += 1
    if row["hdl"] < 40:
        score += 1
    if row["triglycerides"] > 150:
        score += 1
    
    if score >= 3:
        return "High"
    elif score == 2:
        return "Medium"
    else:
        return "Low"


def stroke_risk(row):
    score = 0

    if row["ldl"] > 190 or row["total_cholesterol"] > 300:
        return "Critical"

    if row["ldl"] > 160:
        score += 2
    if row["triglycerides"] > 150:
        score += 1
    if row["total_cholesterol"] > 240:
        score += 2
    
    if score >= 3:
        return "High"
    elif score >= 1:
        return "Medium"
    else:
        return "Low"

In [9]:
lipidProfile["heart_risk"] = lipidProfile.apply(heart_risk, axis=1)
lipidProfile["stroke_risk"] = lipidProfile.apply(stroke_risk, axis=1)

In [10]:
LABEL_MAPPING = {
    "Low": "low",
    "Normal": "moderate",
    "Medium": "moderate",
    "High": "high",
    "Critical": "critical"
}

NUM_MAPPING = {
    "low": 0,
    "moderate": 1,
    "high": 2,
    "critical": 3
}

In [11]:
lipidProfile["heart_risk"] = lipidProfile["heart_risk"].map(LABEL_MAPPING)
lipidProfile["stroke_risk"] = lipidProfile["stroke_risk"].map(LABEL_MAPPING)
lipidProfile["heart_risk_num"] = lipidProfile["heart_risk"].map(NUM_MAPPING)
lipidProfile["stroke_risk_num"] = lipidProfile["stroke_risk"].map(NUM_MAPPING)
lipidProfile.head()

,total_cholesterol,hdl,ldl,triglycerides,vldl,heart_risk,stroke_risk,heart_risk_num,stroke_risk_num
0,213.34,44.15,146.48,100.16,20.53,moderate,low,1,0
1,175.65,62.89,91.62,103.54,21.51,low,low,0,0
2,268.11,55.96,179.58,160.14,37.01,high,high,2,2
3,231.00,74.90,140.59,105.42,20.53,moderate,low,1,0
4,255.20,64.16,166.93,95.75,18.51,moderate,high,1,2